apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: taskflow

spec:
  replicas: 2

  selector:
    matchLabels:
      app: taskflow-frontend

  template:
    metadata:
      labels:
        app: taskflow-frontend

    spec:
      containers:
        - name: frontend
          image: 704348946409.dkr.ecr.ap-south-1.amazonaws.com/taskflow-frontend:b20866ee3c1d3a4003e4e92a9ae159272630a4f4

          ports:
            - containerPort: 80
